name: deep_learn
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py36h68aa20f_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyh44b312d_0
  - ca-certificates=2020.12.5=h5b45459_0
  - certifi=2020.12.5=py36ha15d459_1
  - cffi=1.14.5=py36he58ceb7_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freeglut=3.2.1=h0e60522_2
  - freetype=2.10.4=h546665d_1
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=68.1=h0e60522_0
  - importlib-metadata=3.7.3=py36ha15d459_0
  - intel-openmp=2020.3=h57928b3_311
  - ipykernel=5.5.0=py36h7b2dad6_1
  - ipython=5.8.0=py36_1
  - ipython_genutils=0.2.0=py_1
  - jasper=2.0.14=h77af90b_2
  - jinja2=2.11.3=pyh44b312d_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h8ffe710_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py36ha15d459_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - kiwisolver=1.3.1=py36he95197e_1
  - lcms2=2.12=h2a16943_0
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libclang=11.1.0=default_h5c34c98_0
  - liblapack=3.9.0=8_mkl
  - liblapacke=3.9.0=8_mkl
  - libopencv=4.5.1=py36ha8f7756_0
  - libpng=1.6.37=h1d00b33_2
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.2.0=hc10be44_0
  - libwebp-base=1.2.0=h8ffe710_1
  - lz4-c=1.9.3=h8ffe710_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py36h68aa20f_3
  - matplotlib=3.3.4=py36ha15d459_0
  - matplotlib-base=3.3.4=py36h1abdf75_0
  - mistune=0.8.4=py36h68aa20f_1003
  - mkl=2020.4=hb70f87d_311
  - mkl-service=2.3.0=py36h196d8e1_0
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py36ha15d459_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - notebook=6.2.0=py36ha15d459_0
  - numpy=1.19.5=py36hd1b969e_1
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.1=py36ha15d459_0
  - openssl=1.1.1j=h8ffe710_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.1.5=py36he38d939_0
  - pandoc=2.12=h8ffe710_0
  - pandocfilters=1.4.2=py_1
  - patsy=0.5.1=py_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.2=py36h9cbe6be_0
  - pip=21.0.1=py36haa95532_0
  - plotly=4.14.3=pyh44b312d_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt_toolkit=1.0.15=py_1
  - py-opencv=4.5.1=py36h7b2dad6_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.8.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py36ha15d459_7
  - pyqt-impl=5.12.3=py36he2d232f_7
  - pyqt5-sip=4.19.18=py36he2d232f_7
  - pyqtchart=5.12=py36he2d232f_7
  - pyqtwebengine=5.12.1=py36he2d232f_7
  - pyrsistent=0.17.3=py36h68aa20f_2
  - python=3.6.13=h3758d61_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytz=2021.1=pyhd8ed1ab_0
  - pywin32=300=py36h68aa20f_0
  - pywinpty=0.5.7=py36h9f0ad1d_1
  - pyzmq=22.0.3=py36h1d5d788_1
  - qt=5.12.9=h5909a2a_4
  - retrying=1.3.3=py_2
  - scikit-learn=0.24.1=py36h63cef00_0
  - scipy=1.5.2=py36h9439919_0
  - seaborn=0.11.1=hd8ed1ab_1
  - seaborn-base=0.11.1=pyhd8ed1ab_1
  - send2trash=1.5.0=py_0
  - setuptools=52.0.0=py36haa95532_0
  - simplegeneric=0.8.1=py_1
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.35.1=h2bbff1b_0
  - statsmodels=0.12.2=py36h6434af4_0
  - terminado=0.9.2=py36ha15d459_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=h8ffe710_1
  - tornado=6.1=py36h68aa20f_1
  - tqdm=4.59.0=pyhd8ed1ab_0
  - traitlets=4.3.3=py36h9f0ad1d_1
  - typing_extensions=3.7.4.3=py_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_1
  - zeromq=4.3.4=h0e60522_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.4.9=h6255e5f_0
  - pip:
    - alembic==1.5.7
    - cliff==3.7.0
    - cmaes==0.8.2
    - cmd2==1.5.0
    - colorlog==4.7.2
    - greenlet==1.0.0
    - mako==1.1.4
    - optuna==2.6.0
    - pbr==5.5.1
    - prettytable==2.1.0
    - pyperclip==1.8.2
    - pyreadline==2.1
    - python-editor==1.0.4
    - pyyaml==5.4.1
    - sqlalchemy==1.4.0
    - stevedore==3.3.0
